### ISSUE TITLE
Games/Discover Page  carosuel aligned left; set content div left-margin to "auto" to align center

### ISSUE THREAD

**Issue by randomguyingithub** [Thomasluigi07/SKEUOROBLOX#1]
original
![jlxb38R3dK](https://github.com/Thomasluigi07/SKEUOROBLOX/assets/13596387/04fe5b3c-4969-4d93-b42e-ecb97e94bc7c)

after
![firefox_2404131658_x5hL3](https://github.com/Thomasluigi07/SKEUOROBLOX/assets/13596387/25f70459-0788-4baf-aa71-0ae7d101327a)

code (Section 10)
![uqQJC6Sq13](https://github.com/Thomasluigi07/SKEUOROBLOX/assets/13596387/56b8359f-5014-499b-8fa8-fbb05170bdbe)

```
    .no-gutter-ads.logged-in .content {
        margin-left:auto !important;
    }
```

---
Related code which caused the problem in the first place:

![ux6XNd7HCM](https://github.com/Thomasluigi07/SKEUOROBLOX/assets/13596387/8e386449-c469-4e07-b14f-8bb28deef8a8)

**Comment by Tamasina07** [comment]
Thanks. I've implemented this in the latest version, you'll need to update the style when it releases. Sorry for not reading this, I didn't get a notification.

**Comment by Tamasina07** [comment]
Updated this to only run when the sidebar is shown, and only when logged in. This way it doesnt break small screen resolutions and logged out stuff.
